### ISSUE TITLE
add LSOApop package after renamed

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/universe#2]

**Comment by Lextuga007** [comment]
NHS-R Slack group suggests NHSRpopestimates as capitalised at the end is not good. NHSRpopulationestimates may be too long.

**Comment by tomjemmett** [comment]
https://github.com/nhs-r-community/LSOApop/issues/14 will enable this to be implemented

**Comment by Lextuga007** [comment]
Renamed to NHSRpopulation so this can be added.

**Comment by tomjemmett** [comment]
I've added in https://github.com/nhs-r-community/universe/commit/5d314696f547d45802a860ce4fce7b46f71df2ab
